POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "Can We Stop Pretending Like Abortions Dont Feel Good?",
    "author": "Nicole Mullen",
    "url": "https://night.channel/can-we-stop-pretending-like-abortions-dont-feel-good/",
    "likes": 1000000,
    "userId": "689a77a3958ec74c06df7bf0"
}