POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "A Mommy Blogger’s Open Letter To Iran",
    "author": "Nicole Mullen",
    "url": "https://night.channel/a-mommy-bloggers-open-letter-to-iran/",
    "likes": 3000
}